import data.Course
import data.Request
import data.Teacher
import kotlinx.css.li
import org.appchallenge2024.schedule.plugins.HashMapData
import org.appchallenge2024.schedule.plugins.RequestCompressed
import org.appchallenge2024.schedule.plugins.convertSingleToMultipleRequests
import org.appchallenge2024.schedule.plugins.isCompleteSchedule

data class RawSet(val courses: List<Course>, val requests: List<RequestCompressed>, val teachers: List<Teacher>)

fun convertRawToMap(courses: List<Course>, requests: List<RequestCompressed>, teachers: List<Teacher>): HashMapData {
    val coursesMap = hashMapOf<String, Course>()
    courses.forEach {
        coursesMap[it.id] = it
    }
    val requestsMap = hashMapOf<String, RequestCompressed>()
    requests.forEach {
        requestsMap[it.studentID] = it
    }
    val teachersMap = hashMapOf<String, Teacher>()
    teachers.forEach {
        teachersMap[it.id] = it
    }
    return HashMapData(coursesMap, requestsMap, teachersMap)
}

fun getRaw1(): RawSet {
    val courses = listOf(
        Course("1", "ALG2-OL", "OL Alg 2", "Math"),
        Course("1", "ALG2-H", "H Alg 2", "Math"),
        Course("1", "PHY-OL", "OL Phy", "Science"),
        Course("1", "PHY-AP", "Ap phy", "Science"),
        Course("1", "WORLD-OL", "OL World", "History"),
        Course("1", "WORLD-AP", "Ap world", "History"),
        Course("1", "10LIT-OL", "OL Lit", "ELA"),
        Course("1", "10LIT-H", "H Lit", "ELA")
    )
    val requests = listOf(
        Request("", "0", "Student 0","ALG2-H"),
        Request("", "0", "Student 0","PHY-OL"),
        Request("", "0", "Student 0","WORLD-AP"),
        Request("", "0", "Student 0","10LIT-OL"),
        Request("", "1", "Student 1","ALG2-OL"),
        Request("", "1", "Student 1","PHY-OL"),
        Request("", "1", "Student 1","WORLD-OL"),
//        Request("", "1", "Student 1","10LIT-OL"),
//        Request("", "2", "Student 2","ALG2-H"),
//        Request("", "2", "Student 2","PHY-AP"),
        Request("", "2", "Student 2","WORLD-AP"),
        Request("", "2", "Student 2","10LIT-H"),
        Request("", "3", "Student 3","ALG2-OL"),
        Request("", "3", "Student 3","PHY-AP"),
        Request("", "3", "Student 3","WORLD-AP"),
        Request("", "3", "Student 3","10LIT-H"),
        Request("", "4", "Student 4","ALG2-OL"),
        Request("", "4", "Student 4","PHY-AP"),
        Request("", "4", "Student 4","WORLD-AP"),
        Request("", "4", "Student 4","10LIT-OL"),
        Request("", "5", "Student 5","ALG2-H"),
        Request("", "5", "Student 5","PHY-AP"),
        Request("", "5", "Student 5","WORLD-AP"),
        Request("", "5", "Student 5","10LIT-H"),
        Request("", "6", "Student 6","ALG2-H"),
        Request("", "6", "Student 6","PHY-AP"),
        Request("", "6", "Student 6","WORLD-OL"),
        Request("", "6", "Student 6","10LIT-H"),
        Request("", "7", "Student 7","ALG2-OL"),
        Request("", "7", "Student 7","PHY-OL"),
        Request("", "7", "Student 7","WORLD-OL"),
        Request("", "7", "Student 7","10LIT-H"),
        Request("", "8", "Student 8","ALG2-H"),
        Request("", "8", "Student 8","PHY-OL"),
        Request("", "8", "Student 8","WORLD-OL"),
        Request("", "8", "Student 8","10LIT-OL"),
        Request("", "9", "Student 9","ALG2-OL"),
        Request("", "9", "Student 9","PHY-AP"),
        Request("", "9", "Student 9","WORLD-OL"),
        Request("", "9", "Student 9","10LIT-H"),
    )
    val teachers = listOf(
        Teacher("1", "0", "Robert (Math)", "100", "5", "Math"),
        Teacher("1", "1", "John (Science)", "101", "4", "Science"),
        Teacher("1", "2", "James (History)", "102", "5", "History"),
        Teacher("1", "3", "Justin (ELA)", "103", "4", "ELA")
    )
    return RawSet(courses, convertSingleToMultipleRequests(requests), teachers)
}

fun getRaw2(): RawSet {
    val courses = listOf (
        Course("1", "ALG2-OL", "OL Alg 2", "Math"),
        Course("1", "ALG2-H", "H Alg 2", "Math"),
        Course("1", "PHY-OL", "OL Phy", "Science"),
        Course("1", "PHY-AP1", "Ap phy", "Science"),
        Course("1", "WORLD-OL", "OL World", "History"),
        Course("1", "WORLD-AP", "Ap world", "History"),
        Course("1", "10LIT-OL", "OL Lit", "ELA"),
        Course("1", "10LIT-H", "H Lit", "ELA")
    )
    val requests = listOf(
        Request("", "0", "Alexander Turner","ALG2-H"),
        Request("", "0", "Alexander Turner","PHY-OL"),
        Request("", "0", "Alexander Turner","WORLD-OL"),
        Request("", "0", "Alexander Turner","10LIT-H"),
        Request("", "1", "David Edwards","ALG2-H"),
        Request("", "1", "David Edwards","PHY-AP1"),
        Request("", "1", "David Edwards","WORLD-AP"),
        Request("", "1", "David Edwards","10LIT-H"),
        Request("", "2", "Jennifer Young","ALG2-H"),
        Request("", "2", "Jennifer Young","PHY-AP1"),
        Request("", "2", "Jennifer Young","WORLD-AP"),
        Request("", "2", "Jennifer Young","10LIT-H"),
        Request("", "3", "Justin Jimenez","ALG2-H"),
        Request("", "3", "Justin Jimenez","PHY-OL"),
        Request("", "3", "Justin Jimenez","WORLD-OL"),
        Request("", "3", "Justin Jimenez","10LIT-H"),
        Request("", "4", "Stephen Nguyen","ALG2-OL"),
        Request("", "4", "Stephen Nguyen","PHY-AP1"),
        Request("", "4", "Stephen Nguyen","WORLD-OL"),
        Request("", "4", "Stephen Nguyen","10LIT-OL"),
        Request("", "5", "Scott Ortiz","ALG2-H"),
        Request("", "5", "Scott Ortiz","PHY-AP1"),
        Request("", "5", "Scott Ortiz","WORLD-AP"),
        Request("", "5", "Scott Ortiz","10LIT-H"),
        Request("", "6", "Edward Hall","ALG2-H"),
        Request("", "6", "Edward Hall","PHY-AP1"),
        Request("", "6", "Edward Hall","WORLD-AP"),
        Request("", "6", "Edward Hall","10LIT-H"),
        Request("", "7", "Edward James","ALG2-H"),
        Request("", "7", "Edward James","PHY-OL"),
        Request("", "7", "Edward James","WORLD-OL"),
        Request("", "7", "Edward James","10LIT-H"),
        Request("", "8", "Shirley Stewart","ALG2-OL"),
        Request("", "8", "Shirley Stewart","PHY-AP1"),
        Request("", "8", "Shirley Stewart","WORLD-OL"),
        Request("", "8", "Shirley Stewart","10LIT-OL"),
        Request("", "9", "Catherine Davis","ALG2-OL"),
        Request("", "9", "Catherine Davis","PHY-OL"),
        Request("", "9", "Catherine Davis","WORLD-OL"),
        Request("", "9", "Catherine Davis","10LIT-OL"),
        Request("", "10", "Joshua Walker","ALG2-H"),
        Request("", "10", "Joshua Walker","PHY-AP1"),
        Request("", "10", "Joshua Walker","WORLD-AP"),
        Request("", "10", "Joshua Walker","10LIT-OL"),
        Request("", "11", "Nicole Murphy","ALG2-H"),
        Request("", "11", "Nicole Murphy","PHY-AP1"),
        Request("", "11", "Nicole Murphy","WORLD-AP"),
        Request("", "11", "Nicole Murphy","10LIT-H"),
        Request("", "12", "Michael Ramos","ALG2-H"),
        Request("", "12", "Michael Ramos","PHY-OL"),
        Request("", "12", "Michael Ramos","WORLD-OL"),
        Request("", "12", "Michael Ramos","10LIT-H"),
        Request("", "13", "Charles Thomas","ALG2-H"),
        Request("", "13", "Charles Thomas","PHY-AP1"),
        Request("", "13", "Charles Thomas","WORLD-OL"),
        Request("", "13", "Charles Thomas","10LIT-OL"),
        Request("", "14", "Kenneth Ross","ALG2-OL"),
        Request("", "14", "Kenneth Ross","PHY-OL"),
        Request("", "14", "Kenneth Ross","WORLD-OL"),
        Request("", "14", "Kenneth Ross","10LIT-H"),
        Request("", "15", "Amanda Lee","ALG2-H"),
        Request("", "15", "Amanda Lee","PHY-OL"),
        Request("", "15", "Amanda Lee","WORLD-OL"),
        Request("", "15", "Amanda Lee","10LIT-H"),
        Request("", "16", "Carol Gray","ALG2-OL"),
        Request("", "16", "Carol Gray","PHY-AP1"),
        Request("", "16", "Carol Gray","WORLD-AP"),
        Request("", "16", "Carol Gray","10LIT-OL"),
        Request("", "17", "Ryan Nelson","ALG2-OL"),
        Request("", "17", "Ryan Nelson","PHY-AP1"),
        Request("", "17", "Ryan Nelson","WORLD-AP"),
        Request("", "17", "Ryan Nelson","10LIT-H"),
        Request("", "18", "Sarah Perez","ALG2-OL"),
        Request("", "18", "Sarah Perez","PHY-AP1"),
        Request("", "18", "Sarah Perez","WORLD-OL"),
        Request("", "18", "Sarah Perez","10LIT-H"),
        Request("", "19", "Rebecca Kim","ALG2-H"),
        Request("", "19", "Rebecca Kim","PHY-AP1"),
        Request("", "19", "Rebecca Kim","WORLD-OL"),
        Request("", "19", "Rebecca Kim","10LIT-OL"),
        Request("", "20", "Catherine Hernandez","ALG2-OL"),
        Request("", "20", "Catherine Hernandez","PHY-AP1"),
        Request("", "20", "Catherine Hernandez","WORLD-OL"),
        Request("", "20", "Catherine Hernandez","10LIT-H"),
        Request("", "21", "Jerry Ruiz","ALG2-OL"),
        Request("", "21", "Jerry Ruiz","PHY-AP1"),
        Request("", "21", "Jerry Ruiz","WORLD-AP"),
        Request("", "21", "Jerry Ruiz","10LIT-H"),
        Request("", "22", "Thomas Campbell","ALG2-OL"),
        Request("", "22", "Thomas Campbell","PHY-OL"),
        Request("", "22", "Thomas Campbell","WORLD-AP"),
        Request("", "22", "Thomas Campbell","10LIT-H"),
        Request("", "23", "Nancy Roberts","ALG2-OL"),
        Request("", "23", "Nancy Roberts","PHY-OL"),
        Request("", "23", "Nancy Roberts","WORLD-AP"),
        Request("", "23", "Nancy Roberts","10LIT-OL"),
        Request("", "24", "Ryan Cruz","ALG2-H"),
        Request("", "24", "Ryan Cruz","PHY-OL"),
        Request("", "24", "Ryan Cruz","WORLD-OL"),
        Request("", "24", "Ryan Cruz","10LIT-OL"),
        Request("", "25", "Patricia Baker","ALG2-H"),
        Request("", "25", "Patricia Baker","PHY-OL"),
        Request("", "25", "Patricia Baker","WORLD-AP"),
        Request("", "25", "Patricia Baker","10LIT-OL"),
        Request("", "26", "David Thompson","ALG2-H"),
        Request("", "26", "David Thompson","PHY-OL"),
        Request("", "26", "David Thompson","WORLD-AP"),
        Request("", "26", "David Thompson","10LIT-H"),
        Request("", "27", "Angela Campbell","ALG2-OL"),
        Request("", "27", "Angela Campbell","PHY-AP1"),
        Request("", "27", "Angela Campbell","WORLD-AP"),
        Request("", "27", "Angela Campbell","10LIT-OL"),
        Request("", "28", "Tyler Flores","ALG2-H"),
        Request("", "28", "Tyler Flores","PHY-OL"),
        Request("", "28", "Tyler Flores","WORLD-OL"),
        Request("", "28", "Tyler Flores","10LIT-H"),
        Request("", "29", "Brenda Parker","ALG2-OL"),
        Request("", "29", "Brenda Parker","PHY-OL"),
        Request("", "29", "Brenda Parker","WORLD-AP"),
        Request("", "29", "Brenda Parker","10LIT-H"),
        Request("", "30", "Jeffrey Myers","ALG2-H"),
        Request("", "30", "Jeffrey Myers","PHY-AP1"),
        Request("", "30", "Jeffrey Myers","WORLD-AP"),
        Request("", "30", "Jeffrey Myers","10LIT-H"),
        Request("", "31", "Robert Morgan","ALG2-OL"),
        Request("", "31", "Robert Morgan","PHY-AP1"),
        Request("", "31", "Robert Morgan","WORLD-AP"),
        Request("", "31", "Robert Morgan","10LIT-OL"),
        Request("", "32", "James Cooper","ALG2-OL"),
        Request("", "32", "James Cooper","PHY-OL"),
        Request("", "32", "James Cooper","WORLD-OL"),
        Request("", "32", "James Cooper","10LIT-OL"),
        Request("", "33", "Virginia Baker","ALG2-H"),
        Request("", "33", "Virginia Baker","PHY-AP1"),
        Request("", "33", "Virginia Baker","WORLD-AP"),
        Request("", "33", "Virginia Baker","10LIT-H"),
        Request("", "34", "Barbara Garcia","ALG2-H"),
        Request("", "34", "Barbara Garcia","PHY-OL"),
        Request("", "34", "Barbara Garcia","WORLD-AP"),
        Request("", "34", "Barbara Garcia","10LIT-OL"),
        Request("", "35", "Stephen King","ALG2-H"),
        Request("", "35", "Stephen King","PHY-AP1"),
        Request("", "35", "Stephen King","WORLD-AP"),
        Request("", "35", "Stephen King","10LIT-OL"),
        Request("", "36", "Cynthia Price","ALG2-OL"),
        Request("", "36", "Cynthia Price","PHY-OL"),
        Request("", "36", "Cynthia Price","WORLD-AP"),
        Request("", "36", "Cynthia Price","10LIT-H"),
        Request("", "37", "Scott Johnson","ALG2-H"),
        Request("", "37", "Scott Johnson","PHY-AP1"),
        Request("", "37", "Scott Johnson","WORLD-OL"),
        Request("", "37", "Scott Johnson","10LIT-H"),
        Request("", "38", "Joshua Thomas","ALG2-H"),
        Request("", "38", "Joshua Thomas","PHY-AP1"),
        Request("", "38", "Joshua Thomas","WORLD-OL"),
        Request("", "38", "Joshua Thomas","10LIT-H"),
        Request("", "39", "Carolyn Sanchez","ALG2-H"),
        Request("", "39", "Carolyn Sanchez","PHY-OL"),
        Request("", "39", "Carolyn Sanchez","WORLD-OL"),
        Request("", "39", "Carolyn Sanchez","10LIT-OL"),
        Request("", "40", "Carol Jackson","ALG2-H"),
        Request("", "40", "Carol Jackson","PHY-OL"),
        Request("", "40", "Carol Jackson","WORLD-OL"),
        Request("", "40", "Carol Jackson","10LIT-H"),
        Request("", "41", "Helen Jackson","ALG2-H"),
        Request("", "41", "Helen Jackson","PHY-OL"),
        Request("", "41", "Helen Jackson","WORLD-AP"),
        Request("", "41", "Helen Jackson","10LIT-OL"),
        Request("", "42", "Nicholas Martin","ALG2-OL"),
        Request("", "42", "Nicholas Martin","PHY-AP1"),
        Request("", "42", "Nicholas Martin","WORLD-AP"),
        Request("", "42", "Nicholas Martin","10LIT-H"),
        Request("", "43", "Susan Wood","ALG2-OL"),
        Request("", "43", "Susan Wood","PHY-OL"),
        Request("", "43", "Susan Wood","WORLD-OL"),
        Request("", "43", "Susan Wood","10LIT-H"),
        Request("", "44", "Benjamin Wood","ALG2-H"),
        Request("", "44", "Benjamin Wood","PHY-AP1"),
        Request("", "44", "Benjamin Wood","WORLD-AP"),
        Request("", "44", "Benjamin Wood","10LIT-OL"),
        Request("", "45", "Brandon Richardson","ALG2-H"),
        Request("", "45", "Brandon Richardson","PHY-AP1"),
        Request("", "45", "Brandon Richardson","WORLD-OL"),
        Request("", "45", "Brandon Richardson","10LIT-H"),
        Request("", "46", "Kathleen Rogers","ALG2-OL"),
        Request("", "46", "Kathleen Rogers","PHY-AP1"),
        Request("", "46", "Kathleen Rogers","WORLD-AP"),
        Request("", "46", "Kathleen Rogers","10LIT-OL"),
        Request("", "47", "Pamela Carter","ALG2-OL"),
        Request("", "47", "Pamela Carter","PHY-AP1"),
        Request("", "47", "Pamela Carter","WORLD-OL"),
        Request("", "47", "Pamela Carter","10LIT-OL"),
        Request("", "48", "Patrick Jones","ALG2-H"),
        Request("", "48", "Patrick Jones","PHY-OL"),
        Request("", "48", "Patrick Jones","WORLD-AP"),
        Request("", "48", "Patrick Jones","10LIT-H"),
        Request("", "49", "Frank Hall","ALG2-H"),
        Request("", "49", "Frank Hall","PHY-AP1"),
        Request("", "49", "Frank Hall","WORLD-OL"),
        Request("", "49", "Frank Hall","10LIT-H"),
        Request("", "50", "Patricia Bailey","ALG2-H"),
        Request("", "50", "Patricia Bailey","PHY-AP1"),
        Request("", "50", "Patricia Bailey","WORLD-AP"),
        Request("", "50", "Patricia Bailey","10LIT-OL"),
        Request("", "51", "Sarah Baker","ALG2-H"),
        Request("", "51", "Sarah Baker","PHY-AP1"),
        Request("", "51", "Sarah Baker","WORLD-AP"),
        Request("", "51", "Sarah Baker","10LIT-OL"),
        Request("", "52", "Donna Wood","ALG2-H"),
        Request("", "52", "Donna Wood","PHY-OL"),
        Request("", "52", "Donna Wood","WORLD-AP"),
        Request("", "52", "Donna Wood","10LIT-H"),
        Request("", "53", "Rebecca Watson","ALG2-H"),
        Request("", "53", "Rebecca Watson","PHY-OL"),
        Request("", "53", "Rebecca Watson","WORLD-AP"),
        Request("", "53", "Rebecca Watson","10LIT-OL"),
        Request("", "54", "Michelle Ortiz","ALG2-H"),
        Request("", "54", "Michelle Ortiz","PHY-AP1"),
        Request("", "54", "Michelle Ortiz","WORLD-AP"),
        Request("", "54", "Michelle Ortiz","10LIT-H"),
        Request("", "55", "Matthew King","ALG2-OL"),
        Request("", "55", "Matthew King","PHY-OL"),
        Request("", "55", "Matthew King","WORLD-AP"),
        Request("", "55", "Matthew King","10LIT-OL"),
        Request("", "56", "Raymond Carter","ALG2-OL"),
        Request("", "56", "Raymond Carter","PHY-OL"),
        Request("", "56", "Raymond Carter","WORLD-AP"),
        Request("", "56", "Raymond Carter","10LIT-OL"),
        Request("", "57", "Nicholas Mendoza","ALG2-OL"),
        Request("", "57", "Nicholas Mendoza","PHY-AP1"),
        Request("", "57", "Nicholas Mendoza","WORLD-OL"),
        Request("", "57", "Nicholas Mendoza","10LIT-H"),
        Request("", "58", "Justin Alvarez","ALG2-H"),
        Request("", "58", "Justin Alvarez","PHY-OL"),
        Request("", "58", "Justin Alvarez","WORLD-AP"),
        Request("", "58", "Justin Alvarez","10LIT-H"),
        Request("", "59", "Brenda Ortiz","ALG2-H"),
        Request("", "59", "Brenda Ortiz","PHY-AP1"),
        Request("", "59", "Brenda Ortiz","WORLD-OL"),
        Request("", "59", "Brenda Ortiz","10LIT-OL"),
        Request("", "60", "Tyler Alvarez","ALG2-OL"),
        Request("", "60", "Tyler Alvarez","PHY-OL"),
        Request("", "60", "Tyler Alvarez","WORLD-OL"),
        Request("", "60", "Tyler Alvarez","10LIT-H"),
        Request("", "61", "Angela Chavez","ALG2-OL"),
        Request("", "61", "Angela Chavez","PHY-AP1"),
        Request("", "61", "Angela Chavez","WORLD-AP"),
        Request("", "61", "Angela Chavez","10LIT-H"),
        Request("", "62", "Shirley Mitchell","ALG2-OL"),
        Request("", "62", "Shirley Mitchell","PHY-OL"),
        Request("", "62", "Shirley Mitchell","WORLD-AP"),
        Request("", "62", "Shirley Mitchell","10LIT-OL"),
        Request("", "63", "Helen Ortiz","ALG2-H"),
        Request("", "63", "Helen Ortiz","PHY-OL"),
        Request("", "63", "Helen Ortiz","WORLD-OL"),
        Request("", "63", "Helen Ortiz","10LIT-OL"),
        Request("", "64", "Angela Sanders","ALG2-H"),
        Request("", "64", "Angela Sanders","PHY-OL"),
        Request("", "64", "Angela Sanders","WORLD-AP"),
        Request("", "64", "Angela Sanders","10LIT-H"),
        Request("", "65", "Carol Thompson","ALG2-OL"),
        Request("", "65", "Carol Thompson","PHY-AP1"),
        Request("", "65", "Carol Thompson","WORLD-AP"),
        Request("", "65", "Carol Thompson","10LIT-OL"),
        Request("", "66", "Patricia Clark","ALG2-OL"),
        Request("", "66", "Patricia Clark","PHY-OL"),
        Request("", "66", "Patricia Clark","WORLD-AP"),
        Request("", "66", "Patricia Clark","10LIT-OL"),
        Request("", "67", "Thomas Walker","ALG2-H"),
        Request("", "67", "Thomas Walker","PHY-AP1"),
        Request("", "67", "Thomas Walker","WORLD-OL"),
        Request("", "67", "Thomas Walker","10LIT-H"),
        Request("", "68", "Jason Morales","ALG2-H"),
        Request("", "68", "Jason Morales","PHY-AP1"),
        Request("", "68", "Jason Morales","WORLD-AP"),
        Request("", "68", "Jason Morales","10LIT-OL"),
        Request("", "69", "Jerry Garcia","ALG2-H"),
        Request("", "69", "Jerry Garcia","PHY-OL"),
        Request("", "69", "Jerry Garcia","WORLD-OL"),
        Request("", "69", "Jerry Garcia","10LIT-H"),
        Request("", "70", "Betty Adams","ALG2-H"),
        Request("", "70", "Betty Adams","PHY-OL"),
        Request("", "70", "Betty Adams","WORLD-OL"),
        Request("", "70", "Betty Adams","10LIT-OL"),
        Request("", "71", "Rebecca Hall","ALG2-H"),
        Request("", "71", "Rebecca Hall","PHY-AP1"),
        Request("", "71", "Rebecca Hall","WORLD-AP"),
        Request("", "71", "Rebecca Hall","10LIT-H"),
        Request("", "72", "Brenda Long","ALG2-OL"),
        Request("", "72", "Brenda Long","PHY-OL"),
        Request("", "72", "Brenda Long","WORLD-AP"),
        Request("", "72", "Brenda Long","10LIT-H"),
        Request("", "73", "Christine Collins","ALG2-OL"),
        Request("", "73", "Christine Collins","PHY-AP1"),
        Request("", "73", "Christine Collins","WORLD-OL"),
        Request("", "73", "Christine Collins","10LIT-OL"),
        Request("", "74", "Jacob Clark","ALG2-H"),
        Request("", "74", "Jacob Clark","PHY-OL"),
        Request("", "74", "Jacob Clark","WORLD-AP"),
        Request("", "74", "Jacob Clark","10LIT-H"),
        Request("", "75", "Stephanie Howard","ALG2-H"),
        Request("", "75", "Stephanie Howard","PHY-AP1"),
        Request("", "75", "Stephanie Howard","WORLD-OL"),
        Request("", "75", "Stephanie Howard","10LIT-OL"),
        Request("", "76", "Ashley Myers","ALG2-H"),
        Request("", "76", "Ashley Myers","PHY-OL"),
        Request("", "76", "Ashley Myers","WORLD-OL"),
        Request("", "76", "Ashley Myers","10LIT-OL"),
        Request("", "77", "Debra Kelly","ALG2-H"),
        Request("", "77", "Debra Kelly","PHY-AP1"),
        Request("", "77", "Debra Kelly","WORLD-AP"),
        Request("", "77", "Debra Kelly","10LIT-OL"),
        Request("", "78", "Benjamin Collins","ALG2-H"),
        Request("", "78", "Benjamin Collins","PHY-AP1"),
        Request("", "78", "Benjamin Collins","WORLD-OL"),
        Request("", "78", "Benjamin Collins","10LIT-OL"),
        Request("", "79", "Charles Miller","ALG2-OL"),
        Request("", "79", "Charles Miller","PHY-OL"),
        Request("", "79", "Charles Miller","WORLD-AP"),
        Request("", "79", "Charles Miller","10LIT-H"),
        Request("", "80", "Katherine Jackson","ALG2-H"),
        Request("", "80", "Katherine Jackson","PHY-AP1"),
        Request("", "80", "Katherine Jackson","WORLD-AP"),
        Request("", "80", "Katherine Jackson","10LIT-OL"),
        Request("", "81", "Brenda Watson","ALG2-OL"),
        Request("", "81", "Brenda Watson","PHY-OL"),
        Request("", "81", "Brenda Watson","WORLD-OL"),
        Request("", "81", "Brenda Watson","10LIT-H"),
        Request("", "82", "Catherine Mitchell","ALG2-OL"),
        Request("", "82", "Catherine Mitchell","PHY-OL"),
        Request("", "82", "Catherine Mitchell","WORLD-AP"),
        Request("", "82", "Catherine Mitchell","10LIT-OL"),
        Request("", "83", "Jonathan Howard","ALG2-OL"),
        Request("", "83", "Jonathan Howard","PHY-OL"),
        Request("", "83", "Jonathan Howard","WORLD-AP"),
        Request("", "83", "Jonathan Howard","10LIT-OL"),
        Request("", "84", "Jonathan Gonzalez","ALG2-H"),
        Request("", "84", "Jonathan Gonzalez","PHY-AP1"),
        Request("", "84", "Jonathan Gonzalez","WORLD-AP"),
        Request("", "84", "Jonathan Gonzalez","10LIT-H"),
        Request("", "85", "Pamela Peterson","ALG2-OL"),
        Request("", "85", "Pamela Peterson","PHY-AP1"),
        Request("", "85", "Pamela Peterson","WORLD-AP"),
        Request("", "85", "Pamela Peterson","10LIT-OL"),
        Request("", "86", "Sandra Hernandez","ALG2-H"),
        Request("", "86", "Sandra Hernandez","PHY-OL"),
        Request("", "86", "Sandra Hernandez","WORLD-AP"),
        Request("", "86", "Sandra Hernandez","10LIT-OL"),
        Request("", "87", "Joshua Cox","ALG2-H"),
        Request("", "87", "Joshua Cox","PHY-AP1"),
        Request("", "87", "Joshua Cox","WORLD-OL"),
        Request("", "87", "Joshua Cox","10LIT-H"),
        Request("", "88", "Justin Gonzalez","ALG2-OL"),
        Request("", "88", "Justin Gonzalez","PHY-AP1"),
        Request("", "88", "Justin Gonzalez","WORLD-OL"),
        Request("", "88", "Justin Gonzalez","10LIT-H"),
        Request("", "89", "Jeffrey Harris","ALG2-OL"),
        Request("", "89", "Jeffrey Harris","PHY-OL"),
        Request("", "89", "Jeffrey Harris","WORLD-OL"),
        Request("", "89", "Jeffrey Harris","10LIT-OL"),
        Request("", "90", "Carolyn Bennett","ALG2-OL"),
        Request("", "90", "Carolyn Bennett","PHY-AP1"),
        Request("", "90", "Carolyn Bennett","WORLD-AP"),
        Request("", "90", "Carolyn Bennett","10LIT-OL"),
        Request("", "91", "Scott Parker","ALG2-H"),
        Request("", "91", "Scott Parker","PHY-AP1"),
        Request("", "91", "Scott Parker","WORLD-OL"),
        Request("", "91", "Scott Parker","10LIT-H"),
        Request("", "92", "Karen Jackson","ALG2-H"),
        Request("", "92", "Karen Jackson","PHY-AP1"),
        Request("", "92", "Karen Jackson","WORLD-OL"),
        Request("", "92", "Karen Jackson","10LIT-H"),
        Request("", "93", "Charles Clark","ALG2-OL"),
        Request("", "93", "Charles Clark","PHY-AP1"),
        Request("", "93", "Charles Clark","WORLD-AP"),
        Request("", "93", "Charles Clark","10LIT-H"),
        Request("", "94", "Mark Kelly","ALG2-OL"),
        Request("", "94", "Mark Kelly","PHY-OL"),
        Request("", "94", "Mark Kelly","WORLD-AP"),
        Request("", "94", "Mark Kelly","10LIT-H"),
        Request("", "95", "Donna Nguyen","ALG2-OL"),
        Request("", "95", "Donna Nguyen","PHY-AP1"),
        Request("", "95", "Donna Nguyen","WORLD-AP"),
        Request("", "95", "Donna Nguyen","10LIT-OL"),
        Request("", "96", "Rebecca Bennett","ALG2-OL"),
        Request("", "96", "Rebecca Bennett","PHY-OL"),
        Request("", "96", "Rebecca Bennett","WORLD-OL"),
        Request("", "96", "Rebecca Bennett","10LIT-OL"),
        Request("", "97", "Emily Anderson","ALG2-OL"),
        Request("", "97", "Emily Anderson","PHY-OL"),
        Request("", "97", "Emily Anderson","WORLD-AP"),
        Request("", "97", "Emily Anderson","10LIT-OL"),
        Request("", "98", "Carol Rogers","ALG2-OL"),
        Request("", "98", "Carol Rogers","PHY-OL"),
        Request("", "98", "Carol Rogers","WORLD-AP"),
        Request("", "98", "Carol Rogers","10LIT-H"),
        Request("", "99", "Rebecca Ward","ALG2-H"),
        Request("", "99", "Rebecca Ward","PHY-OL"),
        Request("", "99", "Rebecca Ward","WORLD-OL"),
        Request("", "99", "Rebecca Ward","10LIT-H"),
    )
    val teachers = listOf(
        Teacher("1", "0", "Robert (Math)", "100", "30", "Math"),
        Teacher("1", "1", "John (Science)", "101", "40", "Science"),
        Teacher("1", "2", "James (History)", "102", "30", "History"),
        Teacher("1", "3", "Justin (ELA)", "103", "40", "ELA"),
        Teacher("1", "4", "Robert (Math)", "100", "30", "Math"),
        Teacher("1", "5", "John (Science)", "101", "40", "Science"),
        Teacher("1", "6", "James (History)", "102", "30", "History"),
        Teacher("1", "7", "Jessie (ELA)", "103", "40", "ELA"),

    )
    return RawSet(courses, convertSingleToMultipleRequests(requests), teachers)
}